version: 0.0
os: linux
files:
  - source: ./
    destination: /
hooks:
  BeforeInstall:
    - location: ./ready.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: ./start.sh
      timeout: 60
      runas: root
