name : Deploy Image to AWS
on :
  push:
    branches:
      - githubAction
jobs :
  build:
    runs-on: ubuntu-latest
    steps:
      - name: branch checkout
        uses: actions/checkout@v2

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: docker-spring-mysql
          IMAGE_TAG: 1
        run: |
          # Build a docker image and push it to ECR 
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:spring -f Dockerfile .
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:db -f Dockerfile.mysql .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:spring
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:db

      - name: Upload Docker Compose to S3
        run: |
          aws s3 cp docker-compose.yml s3://solsol-springboot-s3/docker-compose.yml
