name : Deploy Image to AWS
on :
  push:
    branches:
      - githubAction
jobs :
  build:
    runs-on: ubuntu-latest
    steps:
      - name: branch checkout
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name : Gradle Build
        run: ./gradlew build -x test |
          docker-compose build

      - name: Push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: docker-spring-mysql
          IMAGE_TAG: 1
        run: echo "Pushing image to ECR..." |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


