name : Deploy Image to AWS
on :
  push:
    branches:
      - githubAction
jobs :
  build:
    runs-on: ubuntu-latest
    steps:
      - name: branch checkout
        uses: actions/checkout@v2

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: docker-spring-mysql
          IMAGE_TAG: 1
        run: |
          # Build a docker container and push it to ECR 
          docker-compose build
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: branch checkout
        uses: actions/checkout@v2

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-northeast-2

      - name: Authenticate with AWS ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 636000351401.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Pull Image from ECR
        run: |
          docker pull 636000351401.dkr.ecr.ap-northeast-2.amazonaws.com/docker-spring-mysql:1

      - name: Copy Docker Compose File
        run: |
          scp -i /path/to/your/key.pem /path/to/your/docker-compose.yml ubuntu@ec2-54-180-96-148.ap-northeast-2.compute.amazonaws.com:/home/ubuntu/docker-compose.yml
